/* tslint:disable */
/* eslint-disable */
/**
 * ServerC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFeatureInput
 */
export interface CreateFeatureInput {
    /**
     * 
     * @type {string}
     * @memberof CreateFeatureInput
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateFeatureInput
     */
    companyId?: number;
}

/**
 * Check if a given object implements the CreateFeatureInput interface.
 */
export function instanceOfCreateFeatureInput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateFeatureInputFromJSON(json: any): CreateFeatureInput {
    return CreateFeatureInputFromJSONTyped(json, false);
}

export function CreateFeatureInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFeatureInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'companyId': !exists(json, 'companyId') ? undefined : json['companyId'],
    };
}

export function CreateFeatureInputToJSON(value?: CreateFeatureInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'companyId': value.companyId,
    };
}

