/* tslint:disable */
/* eslint-disable */
/**
 * ServerC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTestRunInput
 */
export interface CreateTestRunInput {
    /**
     * 
     * @type {string}
     * @memberof CreateTestRunInput
     */
    name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CreateTestRunInput
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof CreateTestRunInput
     */
    userId?: number;
    /**
     * 
     * @type {Date}
     * @memberof CreateTestRunInput
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateTestRunInput
     */
    endTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof CreateTestRunInput
     */
    testRunStatus?: number;
}

/**
 * Check if a given object implements the CreateTestRunInput interface.
 */
export function instanceOfCreateTestRunInput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateTestRunInputFromJSON(json: any): CreateTestRunInput {
    return CreateTestRunInputFromJSONTyped(json, false);
}

export function CreateTestRunInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTestRunInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'startTime': !exists(json, 'startTime') ? undefined : (new Date(json['startTime'])),
        'endTime': !exists(json, 'endTime') ? undefined : (new Date(json['endTime'])),
        'testRunStatus': !exists(json, 'testRunStatus') ? undefined : json['testRunStatus'],
    };
}

export function CreateTestRunInputToJSON(value?: CreateTestRunInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
        'userId': value.userId,
        'startTime': value.startTime === undefined ? undefined : (value.startTime.toISOString()),
        'endTime': value.endTime === undefined ? undefined : (value.endTime.toISOString()),
        'testRunStatus': value.testRunStatus,
    };
}

