/* tslint:disable */
/* eslint-disable */
/**
 * ServerC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserInput
 */
export interface CreateUserInput {
    /**
     * 
     * @type {string}
     * @memberof CreateUserInput
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUserInput
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUserInput
     */
    password?: string | null;
}

/**
 * Check if a given object implements the CreateUserInput interface.
 */
export function instanceOfCreateUserInput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateUserInputFromJSON(json: any): CreateUserInput {
    return CreateUserInputFromJSONTyped(json, false);
}

export function CreateUserInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function CreateUserInputToJSON(value?: CreateUserInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
        'password': value.password,
    };
}

