/* tslint:disable */
/* eslint-disable */
/**
 * ServerC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTestResultInput
 */
export interface CreateTestResultInput {
    /**
     * 
     * @type {number}
     * @memberof CreateTestResultInput
     */
    featureId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateTestResultInput
     */
    resultsJson?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateTestResultInput
     */
    userId?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof CreateTestResultInput
     */
    date?: Date | null;
}

/**
 * Check if a given object implements the CreateTestResultInput interface.
 */
export function instanceOfCreateTestResultInput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateTestResultInputFromJSON(json: any): CreateTestResultInput {
    return CreateTestResultInputFromJSONTyped(json, false);
}

export function CreateTestResultInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTestResultInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'featureId': !exists(json, 'featureId') ? undefined : json['featureId'],
        'resultsJson': !exists(json, 'resultsJson') ? undefined : json['resultsJson'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'date': !exists(json, 'date') ? undefined : (json['date'] === null ? null : new Date(json['date'])),
    };
}

export function CreateTestResultInputToJSON(value?: CreateTestResultInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'featureId': value.featureId,
        'resultsJson': value.resultsJson,
        'userId': value.userId,
        'date': value.date === undefined ? undefined : (value.date === null ? null : value.date.toISOString()),
    };
}

