/* tslint:disable */
/* eslint-disable */
/**
 * ServerC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TestRunCase
 */
export interface TestRunCase {
    /**
     * 
     * @type {number}
     * @memberof TestRunCase
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof TestRunCase
     */
    testRunId?: number;
    /**
     * 
     * @type {number}
     * @memberof TestRunCase
     */
    testCaseId?: number;
    /**
     * 
     * @type {number}
     * @memberof TestRunCase
     */
    testCaseStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof TestRunCase
     */
    testCaseComment?: string | null;
}

/**
 * Check if a given object implements the TestRunCase interface.
 */
export function instanceOfTestRunCase(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TestRunCaseFromJSON(json: any): TestRunCase {
    return TestRunCaseFromJSONTyped(json, false);
}

export function TestRunCaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestRunCase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'testRunId': !exists(json, 'testRunId') ? undefined : json['testRunId'],
        'testCaseId': !exists(json, 'testCaseId') ? undefined : json['testCaseId'],
        'testCaseStatus': !exists(json, 'testCaseStatus') ? undefined : json['testCaseStatus'],
        'testCaseComment': !exists(json, 'testCaseComment') ? undefined : json['testCaseComment'],
    };
}

export function TestRunCaseToJSON(value?: TestRunCase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'testRunId': value.testRunId,
        'testCaseId': value.testCaseId,
        'testCaseStatus': value.testCaseStatus,
        'testCaseComment': value.testCaseComment,
    };
}

