/* tslint:disable */
/* eslint-disable */
/**
 * ServerC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTestCaseInput
 */
export interface UpdateTestCaseInput {
    /**
     * 
     * @type {number}
     * @memberof UpdateTestCaseInput
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateTestCaseInput
     */
    featureId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTestCaseInput
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateTestCaseInput
     */
    sortOrder?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateTestCaseInput
     */
    parentId?: number | null;
}

/**
 * Check if a given object implements the UpdateTestCaseInput interface.
 */
export function instanceOfUpdateTestCaseInput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateTestCaseInputFromJSON(json: any): UpdateTestCaseInput {
    return UpdateTestCaseInputFromJSONTyped(json, false);
}

export function UpdateTestCaseInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTestCaseInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'featureId': !exists(json, 'featureId') ? undefined : json['featureId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'sortOrder': !exists(json, 'sortOrder') ? undefined : json['sortOrder'],
        'parentId': !exists(json, 'parentId') ? undefined : json['parentId'],
    };
}

export function UpdateTestCaseInputToJSON(value?: UpdateTestCaseInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'featureId': value.featureId,
        'name': value.name,
        'sortOrder': value.sortOrder,
        'parentId': value.parentId,
    };
}

