/* tslint:disable */
/* eslint-disable */
/**
 * ServerC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSingleTestResultInput
 */
export interface UpdateSingleTestResultInput {
    /**
     * 
     * @type {number}
     * @memberof UpdateSingleTestResultInput
     */
    testResultId?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateSingleTestResultInput
     */
    singleResultJson?: string | null;
}

/**
 * Check if a given object implements the UpdateSingleTestResultInput interface.
 */
export function instanceOfUpdateSingleTestResultInput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateSingleTestResultInputFromJSON(json: any): UpdateSingleTestResultInput {
    return UpdateSingleTestResultInputFromJSONTyped(json, false);
}

export function UpdateSingleTestResultInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSingleTestResultInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'testResultId': !exists(json, 'testResultId') ? undefined : json['testResultId'],
        'singleResultJson': !exists(json, 'singleResultJson') ? undefined : json['singleResultJson'],
    };
}

export function UpdateSingleTestResultInputToJSON(value?: UpdateSingleTestResultInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'testResultId': value.testResultId,
        'singleResultJson': value.singleResultJson,
    };
}

