/* tslint:disable */
/* eslint-disable */
/**
 * ServerC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserInput
 */
export interface UpdateUserInput {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInput
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInput
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInput
     */
    password?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateUserInput
     */
    id?: number;
}

/**
 * Check if a given object implements the UpdateUserInput interface.
 */
export function instanceOfUpdateUserInput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateUserInputFromJSON(json: any): UpdateUserInput {
    return UpdateUserInputFromJSONTyped(json, false);
}

export function UpdateUserInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function UpdateUserInputToJSON(value?: UpdateUserInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
        'password': value.password,
        'id': value.id,
    };
}

